### PR TITLE
Tidy custom groups up box displayed on users profile

### PR DESCRIPTION
**Pull request by htmgarcia**
#480

Generated result:
Screen Shot 2021-11-12 at 8 52 11

### CODE REVIEW

**Review by agapetry — COMMENTED** [review]
@htmgarcia It can be convenient for administrators reviewing a user's groups to have an group edit link to jump into. Can you suggest a more elegant solution than my mouseenter showing?

**Comment by htmgarcia** [comment]
@agapetry may you elaborate?

**Comment by agapetry** [comment]
@htmgarcia That answers my question. I was looking at the code and didn't notice that you showed edit links in the screenshot.

**Comment by htmgarcia** [comment]
Thanks @agapetry !

**Pull request merged**
