### PR TITLE
fix/dev_workspace_docker

### PR DESCRIPTION
**Pull request by richaferry**

### CODE REVIEW

**Comment by agapetry** [comment]
@richaferry The DOCKER_HOST_IP entries are something Anderson added to resolve an access issue I had some time ago. I'm not entirely sure if it is still needed, but am hesitant to put time into experimenting with dev-workspace configuration right now. Do you see a reason to remove this, or are just unsure why it's there?

**Comment by richaferry** [comment]
> @richaferry The DOCKER_HOST_IP entries are something Anderson added to resolve an access issue I had some time ago. I'm not entirely sure if it is still needed, but am hesitant to put time into experimenting with dev-workspace configuration right now. Do you see a reason to remove this, or are just unsure why it's there?

Yes. Previously i got error in my side if yaml config expose that IP. i dont know exactly why. Im using linux ubuntu 22.04.

**Comment by richaferry** [comment]
> @richaferry The DOCKER_HOST_IP entries are something Anderson added to resolve an access issue I had some time ago. I'm not entirely sure if it is still needed, but am hesitant to put time into experimenting with dev-workspace configuration right now. Do you see a reason to remove this, or are just unsure why it's there?

Yes. Previously i got error in my side if yaml config expose that IP. i dont know exactly why. Im using linux ubuntu 22.04.  @agapetry

**Comment by richaferry** [comment]
After trying another solution finally i found it. https://github.com/publishpress/PublishPress-Permissions/pull/1238/commits/189fd1c1dde11537fd91b8f0606929a035814621 @agapetry

**Pull request merged**
